# Generated by Django 4.2.3 on 2023-07-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_livro_capa'),
    ]

    operations = [
        migrations.AddField(
            model_name='genero',
            name='qntLivros',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
