# Generated by Django 4.2.2 on 2023-06-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_carrinho_compra_alter_autor_options_compralivro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
