# Generated by Django 4.2.2 on 2023-06-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_livro_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='isbn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
