# Generated by Django 4.2.3 on 2023-07-14 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_genero_qntlivros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='genre',
            field=models.ManyToManyField(to='app.genero'),
        ),
    ]
