# Generated by Django 4.2.3 on 2023-07-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_livro_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='data_pub',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='paginas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='sinopse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='vendas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='genero',
            name='qntLivros',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
