# Generated by Django 4.2.2 on 2023-06-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_livro_isbn_alter_livro_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
