# Generated by Django 4.2.2 on 2023-06-26 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_carrinho_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinho',
            name='livro',
        ),
    ]
