# Generated by Django 4.2.2 on 2023-06-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_carrinho_livro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='livro',
        ),
        migrations.RemoveField(
            model_name='compralivro',
            name='valor',
        ),
        migrations.AlterField(
            model_name='compra',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
