# Generated by Django 4.2.3 on 2023-07-21 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_coment_livro_coment_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='coment',
            name='livro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.livro'),
            preserve_default=False,
        ),
    ]
