# Generated by Django 4.2.4 on 2023-08-26 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_livro_desconto_alter_compra_total_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
