from .livro import LivroViewSet
from .genero import GeneroViewSet
from .autor import AutorViewSet
from .carrinho import CarrinhoViewSet
from .carrinhoLivro import CarrinhoLivroViewSet
from .compra import CompraViewSet
from .compraLivro import CompraLivroViewSet
from .coment import ComentViewSet
from .favorite import FavoriteViewSet