CREATE TABLE IF NOT EXISTS "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL);
CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE IF NOT EXISTS "django_content_type" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL);
CREATE UNIQUE INDEX "django_content_type_app_label_model_76bd3d3b_uniq" ON "django_content_type" ("app_label", "model");
CREATE TABLE IF NOT EXISTS "auth_group_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" ON "auth_group_permissions" ("group_id", "permission_id");
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id");
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id");
CREATE TABLE IF NOT EXISTS "auth_permission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "content_type_id" integer NOT NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "codename" varchar(100) NOT NULL, "name" varchar(255) NOT NULL);
CREATE UNIQUE INDEX "auth_permission_content_type_id_codename_01ab375a_uniq" ON "auth_permission" ("content_type_id", "codename");
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id");
CREATE TABLE IF NOT EXISTS "auth_group" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(150) NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS "usuario_usuario_groups" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "usuario_id" bigint NOT NULL REFERENCES "usuario_usuario" ("id") DEFERRABLE INITIALLY DEFERRED, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "usuario_usuario_user_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "usuario_id" bigint NOT NULL REFERENCES "usuario_usuario" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "usuario_usuario_groups_usuario_id_group_id_a4cfb0b8_uniq" ON "usuario_usuario_groups" ("usuario_id", "group_id");
CREATE INDEX "usuario_usuario_groups_usuario_id_62de76a1" ON "usuario_usuario_groups" ("usuario_id");
CREATE INDEX "usuario_usuario_groups_group_id_b9c090f8" ON "usuario_usuario_groups" ("group_id");
CREATE UNIQUE INDEX "usuario_usuario_user_permissions_usuario_id_permission_id_c0a85055_uniq" ON "usuario_usuario_user_permissions" ("usuario_id", "permission_id");
CREATE INDEX "usuario_usuario_user_permissions_usuario_id_5969a193" ON "usuario_usuario_user_permissions" ("usuario_id");
CREATE INDEX "usuario_usuario_user_permissions_permission_id_5cad0a4b" ON "usuario_usuario_user_permissions" ("permission_id");
CREATE TABLE IF NOT EXISTS "django_admin_log" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "action_flag" smallint unsigned NOT NULL CHECK ("action_flag" >= 0), "change_message" text NOT NULL, "content_type_id" integer NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" bigint NOT NULL REFERENCES "usuario_usuario" ("id") DEFERRABLE INITIALLY DEFERRED, "action_time" datetime NOT NULL);
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id");
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" ("user_id");
CREATE TABLE IF NOT EXISTS "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" datetime NOT NULL);
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");
CREATE TABLE IF NOT EXISTS "app_carrinholivro" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "quantidade" integer NOT NULL, "carrinho_id" bigint NOT NULL REFERENCES "app_carrinho" ("id") DEFERRABLE INITIALLY DEFERRED, "livro_id" bigint NOT NULL REFERENCES "app_livro" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "app_carrinholivro_carrinho_id_8ead191c" ON "app_carrinholivro" ("carrinho_id");
CREATE INDEX "app_carrinholivro_livro_id_916ff50d" ON "app_carrinholivro" ("livro_id");
CREATE TABLE IF NOT EXISTS "app_carrinho" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" bigint NOT NULL REFERENCES "usuario_usuario" ("id") DEFERRABLE INITIALLY DEFERRED, "total" decimal NOT NULL);
CREATE INDEX "app_carrinho_user_id_c8dfb32f" ON "app_carrinho" ("user_id");
CREATE TABLE IF NOT EXISTS "uploader_document" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "attachment_key" char(32) NOT NULL UNIQUE, "public_id" char(32) NOT NULL UNIQUE, "file" varchar(100) NOT NULL, "description" varchar(255) NOT NULL, "uploaded_on" datetime NOT NULL);
CREATE TABLE IF NOT EXISTS "uploader_image" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "attachment_key" char(32) NOT NULL UNIQUE, "public_id" char(32) NOT NULL UNIQUE, "file" varchar(100) NOT NULL, "description" varchar(255) NOT NULL, "uploaded_on" datetime NOT NULL);
CREATE TABLE IF NOT EXISTS "app_autor" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(100) NOT NULL, "age" varchar(45) NULL);
CREATE TABLE IF NOT EXISTS "app_livro_genre" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "livro_id" bigint NOT NULL REFERENCES "app_livro" ("id") DEFERRABLE INITIALLY DEFERRED, "genero_id" bigint NOT NULL REFERENCES "app_genero" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "app_livro_genre_livro_id_genero_id_74e804fc_uniq" ON "app_livro_genre" ("livro_id", "genero_id");
CREATE INDEX "app_livro_genre_livro_id_67e91c6d" ON "app_livro_genre" ("livro_id");
CREATE INDEX "app_livro_genre_genero_id_c8af1345" ON "app_livro_genre" ("genero_id");
CREATE TABLE IF NOT EXISTS "app_genero" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(100) NOT NULL, "qntLivros" integer NULL);
CREATE TABLE IF NOT EXISTS "app_coment" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "title" varchar(45) NOT NULL, "text" text NOT NULL, "date" datetime NOT NULL, "user_id" bigint NOT NULL REFERENCES "usuario_usuario" ("id") DEFERRABLE INITIALLY DEFERRED, "livro_id" bigint NOT NULL REFERENCES "app_livro" ("id") DEFERRABLE INITIALLY DEFERRED, "stars" integer NOT NULL);
CREATE INDEX "app_coment_user_id_dd549c42" ON "app_coment" ("user_id");
CREATE INDEX "app_coment_livro_id_fbddb00d" ON "app_coment" ("livro_id");
CREATE TABLE IF NOT EXISTS "app_favorite" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "book_id" bigint NOT NULL REFERENCES "app_livro" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" bigint NOT NULL REFERENCES "usuario_usuario" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "app_favorite_book_id_1f6c92b3" ON "app_favorite" ("book_id");
CREATE INDEX "app_favorite_user_id_bd10a641" ON "app_favorite" ("user_id");
CREATE TABLE IF NOT EXISTS "usuario_usuario" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "password" varchar(128) NOT NULL, "last_login" datetime NULL, "is_superuser" bool NOT NULL, "first_name" varchar(150) NOT NULL, "last_name" varchar(150) NOT NULL, "is_staff" bool NOT NULL, "is_active" bool NOT NULL, "date_joined" datetime NOT NULL, "email" varchar(254) NOT NULL UNIQUE, "cpf" varchar(11) NULL, "telefone" varchar(11) NULL, "data_nascimento" date NULL, "username" varchar(50) NOT NULL UNIQUE, "password_reset_token" varchar(6) NULL, "password_reset_token_created" datetime NULL, "foto_id" bigint NULL REFERENCES "uploader_image" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "app_livro" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "title" varchar(100) NOT NULL, "price" decimal NULL, "stock" integer NULL, "isbn" varchar(20) NULL, "author_id" bigint NOT NULL REFERENCES "app_autor" ("id") DEFERRABLE INITIALLY DEFERRED, "data_pub" date NULL, "paginas" integer NULL, "sinopse" text NULL, "vendas" integer NULL, "desconto" decimal NULL, "capa_id" bigint NULL REFERENCES "uploader_image" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "app_livro_author_id_ffe56e38" ON "app_livro" ("author_id");
CREATE TABLE IF NOT EXISTS "app_compra" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" bigint NOT NULL REFERENCES "usuario_usuario" ("id") DEFERRABLE INITIALLY DEFERRED, "total" decimal NOT NULL);
CREATE INDEX "app_compra_user_id_86f7d00a" ON "app_compra" ("user_id");
CREATE TABLE IF NOT EXISTS "app_compralivro" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "compra_id" bigint NOT NULL REFERENCES "app_compra" ("id") DEFERRABLE INITIALLY DEFERRED, "livro_id" bigint NOT NULL REFERENCES "app_livro" ("id") DEFERRABLE INITIALLY DEFERRED, "quantidade" integer NOT NULL);
CREATE INDEX "app_compralivro_compra_id_ab52f2a0" ON "app_compralivro" ("compra_id");
CREATE INDEX "app_compralivro_livro_id_c6b35ae9" ON "app_compralivro" ("livro_id");
CREATE INDEX "app_livro_capa_id_94961026" ON "app_livro" ("capa_id");
CREATE INDEX "usuario_usuario_foto_id_1d9bdbfb" ON "usuario_usuario" ("foto_id");
