# Generated by Django 4.2.2 on 2023-07-01 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_alter_usuario_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='password_reset_token_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
