# Generated by Django 4.2.4 on 2023-08-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_usuario_password_reset_token_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/'),
        ),
    ]
