# Generated by Django 4.2.4 on 2023-08-16 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_usuario_password_reset_token_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='password_reset_token_created',
            new_name='password_reset_token',
        ),
    ]
