# Generated by Django 4.2.4 on 2023-08-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_rename_password_reset_token_created_usuario_password_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='password_reset_token_created',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password_reset_token',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
