# Generated by Django 4.2.4 on 2023-08-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0010_alter_usuario_password_reset_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password_reset_token',
            field=models.CharField(blank=True, default=None, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password_reset_token_created',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
