# Generated by Django 4.2.4 on 2023-08-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0012_alter_usuario_password_reset_token_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='image',
            field=models.ImageField(blank=True, default='usuarios/default.png', null=True, upload_to='usuarios'),
        ),
    ]
