# Generated by Django 4.2.4 on 2023-08-21 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0013_usuario_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='image',
        ),
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.ImageField(blank=True, null=True, upload_to='profileImages/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profileImages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
