# Generated by Django 4.2.4 on 2023-08-25 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0015_alter_profileimage_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileImage',
        ),
    ]
